# Site settings
title: Russell's blog
description: Russell's blog
url: https://rjhalliday.github.io

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
#jekyll-theme-minimal
#

# Additional settings
collections:
  - posts
